variable "subscription_id" {
  description = "Azure subscription ID."
  type        = string
}

variable "tenant_id" {
  description = "Azure tenant ID."
  type        = string
}

variable "resource_group_name" {
  description = "Name of the resource group."
  type        = string
  default     = "rg-procurement-rag"
}

variable "create_resource_group" {
  description = "Set to true to create a new resource group, false to use an existing one. When false, the resource group must already exist."
  type        = bool
  default     = true
}

variable "location" {
  description = "Azure region for resources."
  type        = string
  default     = "swedencentral"
}

variable "environment_name" {
  description = "Environment name for resource naming."
  type        = string
  default     = "poc"
}

variable "unique_suffix" {
  description = "Unique alphanumeric suffix for globally unique resource names. Auto-generated by 00-init-tfvars.ps1."
  type        = string
}

variable "tags" {
  description = "Tags for all resources."
  type        = map(string)
  default     = {}
}

# AI Search
variable "search_sku" {
  description = "AI Search SKU (free, basic, standard)."
  type        = string
  default     = "basic"
}

variable "search_location" {
  description = "Region for AI Search. Override if the main region has capacity issues."
  type        = string
  default     = ""
}

# Embedding model
variable "embedding_model" {
  description = "Embedding model deployment name."
  type        = string
  default     = "text-embedding-ada-002"
}

# SharePoint
variable "sharepoint_site_name" {
  description = "SharePoint site display name."
  type        = string
  default     = "Marches GHT Contoso"
}

variable "sharepoint_site_alias" {
  description = "SharePoint site URL alias (no spaces)."
  type        = string
  default     = "marches-ght-contoso"
}
